### ISSUE TITLE
Broader terms should be selectable from the whole workspace

### ISSUE THREAD

**Issue by psiotwo** [opendata-mvcr/termit#38]
Currently, a workspace is a set of vocabularies which are not necessarily linked by importuje-slovnik link. This link cannot be modified in the current version of assembly line (it was previously possible in TermIt, but the functionality was removed, since vocabulary relationships are a responsibility of control panel).

The goal of this ticket is to make all vocabularies in a workspace reusable: 
1) Parent term should be selectable from all vocabularies in the given workspace.
2) If a parent term was selected that is from a vocabulary A not yet linked from the current vocabulary V (i.e. no other parent term from A is linked from B), user is first provided with a confirmation dialogue informing him that he is establishing a cross-vocabulary link and asking him to confirm her decision.
3) The "A importuje-slovnik B" link is automatically inferred whenever a term from A has a term from B as a parent term. This will allow caching the information about vocabulary dependencies.

---
Example:

In the following workspace:
https://kbss.felk.cvut.cz/termit-kodi/#/vocabularies?workspace=https://slovn%C3%ADk.gov.cz/datov%C3%BD/pracovn%C3%AD-prostor/pojem/metadatov%C3%BD-kontext/instance-521215042

When editing a term from 222/2016 Sb. 
https://kbss.felk.cvut.cz/termit-kodi/#/vocabularies/2016/terms/%C4%8D%C3%A1stka?namespace=https://slovn%C3%ADk.gov.cz/legislativn%C3%AD/sb%C3%ADrka/222/&includeImported=false

Parent term should be selectable from all vocabularies in the given workspace.

**Comment by psiotwo** [comment]
@opendata-mvcr/c5-devs ^ please comment

**Comment by MichalMed** [comment]
Basically you say, that property importuje-slovník remains, but is added automatically after confirmation at the moment, when you for the first time import any term from that vocabulary? What if you are importing second term from the same vocabulary? Are asked again for the confirmation? I would recommend it. Otherwise low-experienced users will add users from multiple various vocabularies even without knowing it. Most probably they will anyway.

I do not like this kind of solution at all, because you will have pears mixed with apples.
